version: "3.7"
services:
  app:
    build:
      dockerfile: ./Dockerfile
      context: .
    entrypoint: /bin/sh -c
    command:
      - |
        /wait
        tail -f /dev/null
    environment:
      REDIS_URL: redis://redis
      WAIT_HOSTS: redis:6379
      WAIT_SLEEP_INTERVAL: 1
      PYTHONPATH: .

  redis:
    image: redis
    ports:
      - "6379:6379"

  redis-commander:
    hostname: redis-commander
    image: rediscommander/redis-commander
    environment:
      REDIS_HOSTS: local:redis:6379
      HTTP_USER: redis
      HTTP_PASSWORD: redis
    ports:
      - "8081:8081"