FROM python:3.7.2
MAINTAINER Szymon Litera <s.litera@gmail.com>
ENV PYTHONUNBUFFERED 1

RUN mkdir /code
WORKDIR /code

ADD requirements-tests.txt /code/
RUN pip install -r requirements-tests.txt
ADD . /code/

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.5.0/wait /wait
RUN chmod +x /wait
